FROM php:8.0-apache

ENV DEBIAN_FRONTEND="noninteractive"


RUN apt-get update && apt-get install -y iputils-ping net-tools git unzip vim
RUN apt-get install apache2-utils
RUN a2enmod rewrite
RUN docker-php-ext-install mysqli pdo pdo_mysql

CMD apachectl -k stop && apachectl -D FOREGROUND
